Remove bloats and full system revamp ✨

diff --git a/bashrc/aliases b/bashrc/aliases
--- a/bashrc/aliases
+++ b/bashrc/aliases
@@ -9,18 +9,26 @@ alias lsa='ls -a'
 alias lt='eza --tree --level=2 --long --icons --git'
 alias lta='lt -a'
 alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
+
 if command -v zoxide &> /dev/null; then
   alias cd="zd"
   zd() {
-    if [ $# -eq 0 ]; then
-      builtin cd ~ && return
-    elif [ -d "$1" ]; then
-      builtin cd "$1"
+    if (( $# == 0 )); then
+      builtin cd ~ || return
+    elif [[ -d $1 ]]; then
+      builtin cd "$1" || return
     else
-      z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+      if ! z "$@"; then
+        echo "Error: Directory not found"
+        return 1
+      fi
+
+      printf "\U000F17A9 "
+      pwd
     fi
   }
 fi
+
 open() {
   xdg-open "$@" >/dev/null 2>&1 &
 }
